drop DATABASE papyrus;
CREATE DATABASE papyrus;
USE papyrus;
CREATE TABLE Produit(
   CODART CHAR(4) NOT NULL,
   LIBART VARCHAR(30) NOT NULL,
   STKALE INT(10) NOT NULL,
   STKPHY INT(10) NOT NULL,
   QTEANN INT(10) NOT NULL,
   UNIMES CHAR(5) NOT NULL,
   PRIMARY KEY(CODART)
);

CREATE TABLE Fournis(
   NUMFOU VARCHAR(25) NOT NULL,
   NOMFOU VARCHAR(25) NOT NULL,
   RUEFOU VARCHAR(50) NOT NULL,
   POSFOU CHAR(5) NOT NULL,
   VILFOU VARCHAR(30) NOT NULL,
   CONFOU VARCHAR(15) NOT NULL,
   SATISF TINYINT(10),
   PRIMARY KEY(NUMFOU)
);

CREATE TABLE Entcom(
   NUMCOM INT(10) NOT NULL AUTO_INCREMENT,
   OBSCOM VARCHAR(50),
   DATCOM DATETIME NOT NULL,
   NUMFOU VARCHAR(25) NOT NULL,
   PRIMARY KEY(NUMCOM),
   FOREIGN KEY(NUMFOU) REFERENCES Fournis(NUMFOU)
);

CREATE INDEX INDEX1 ON Entcom (NUMFOU);

CREATE TABLE Ligcom(
   NUMLIG TINYINT(3) NOT  NULL,
   QTECDE INT(10) NOT NULL,
   PRIUNI VARCHAR(50) NOT NULL,
   QTELIV INT(10),
   DERLIV DATETIME(6) NOT NULL,
   NUMCOM INT(10) NOT NULL,
   CODART CHAR(4) NOT NULL,
   PRIMARY KEY(NUMLIG),
   FOREIGN KEY(NUMCOM) REFERENCES Entcom(NUMCOM),
   FOREIGN KEY(CODART) REFERENCES Produit(CODART)
);

CREATE TABLE Ventes(
   CODART CHAR(4) NOT NULL,
   NUMFOU VARCHAR(25) NOT NULL,
   DELLIV SMALLINT(5) NOT NULL,
   QTE1 INT(10) NOT NULL,
   PRIX1 VARCHAR(50) NOT NULL,
   QTE2 INT(10),
   PRIX2 VARCHAR(50),
   QTE3 INT(10),
   PRIX3 VARCHAR(50),
   PRIMARY KEY(CODART, NUMFOU),
   FOREIGN KEY(CODART) REFERENCES Produit(CODART),
   FOREIGN KEY(NUMFOU) REFERENCES Fournis(NUMFOU)
);
